add graph to OTF ADR and tox env for updating plantuml
GridTools/gt4py pull request #1048
Opened 2022-11-15 11:03 UTC by DropD

## Description

This PR adds the workflow reference graph from the recent internal presentation to the OTF toolchain ADR, exploring a possible standard way to handle graphs in ADRs.

In addition to embedding `plantuml` inside the markdown and linking to the generated SVG file, this PR adds tox automation for updating all ADR plantuml graphs. This currently relies on plantuml CLI being pre-installed and is merely one possible way. Alternatives:

- https://github.com/danielyaa5/puml-for-markdown: does not allow to embed puml directly inside markdown but creates and embeds / linksJK graphs automatically from links to puml files. It does this by using the plantuml server to create a link to the rendered graph. No storing svg files in the repo.
- multiple github actions are available on the Marketplace: https://github.com/marketplace?query=plantuml
- potentially other ones listed at https://plantuml.com/running

2023-01-11 09:31 UTC, egparedes commented
bors try

2023-01-13 15:39 UTC, egparedes requested changes
It is almost ready to go. There are just a couple of typos and the renaming of the tox action.

2023-01-16 09:45 UTC, DropD commented on tox.ini
> +[testenv:dev-adr-plantuml]
Noted, thanks!

2023-01-16 16:03 UTC, egparedes approved these changes
It looks good to me.

2023-01-16 16:25 UTC, egparedes commented
Why are CI tests not running in this PR anymore?

2023-01-18 12:15 UTC, havogt commented
No idea, seems to work after another merge with functional.

2023-01-18 13:52 UTC, merged