Test Python 3.10 on daint
GridTools/gt4py pull request #1087
Opened 2022-12-14 11:03 UTC by havogt

2022-12-14 11:03 UTC, havogt commented
bors try

2022-12-14 12:07 UTC, havogt commented on .gitlab-ci.yml
> +    <<: *py39
```suggestion
    <<: *py310
```

2022-12-14 12:12 UTC, havogt commented
bors try

2022-12-14 12:37 UTC, havogt commented
bors try-

2022-12-14 16:07 UTC, havogt commented
bors try

2022-12-15 08:24 UTC, gronerl requested changes

2022-12-15 11:51 UTC, havogt commented
bors try

2022-12-15 11:51 UTC, gronerl approved these changes

2022-12-19 08:44 UTC, merged