Move AST types to top-level of module
GridTools/gt4py pull request #1091
Opened 2022-12-15 14:52 UTC by petiaccja

2022-12-20 14:36 UTC, tehrengruber requested changes

2022-12-20 14:36 UTC, tehrengruber commented on src/functional/type_system/type_info.py
> +import functools
Copyright header.

2022-12-20 14:36 UTC, tehrengruber commented on src/functional/type_system/type_specifications.py
> +from dataclasses import dataclass
Copyright header.

2022-12-20 14:36 UTC, tehrengruber commented on src/functional/ffront/type_specifications.py
> +from dataclasses import dataclass
Copyright header.

2022-12-20 14:36 UTC, tehrengruber commented on tests/functional_tests/ffront_tests/test_foast_lowering.py
> +import functional.ffront.type_specifications
```suggestion
```
You already have the `ts` alias below.

2022-12-20 14:36 UTC, tehrengruber commented on tests/functional_tests/ffront_tests/test_foast_lowering.py
> +    field_type = from_type_hint(Field[..., float64])
```suggestion
    field_type = type_translation.from_type_hint(Field[..., float64])
```
For consistency.

2022-12-20 14:36 UTC, tehrengruber commented on tests/functional_tests/ffront_tests/test_foast_lowering.py
> +from functional.type_system import type_specifications as ts
```suggestion
from functional.ffront.type_system import type_specifications as ts
```

2022-12-20 14:36 UTC, tehrengruber commented on tests/functional_tests/ffront_tests/test_foast_lowering.py
> +        __gt_type__=lambda: functional.ffront.type_specifications.FieldOperatorType(
```suggestion
        __gt_type__=lambda: ts.FieldOperatorType(
```

2022-12-20 14:36 UTC, tehrengruber commented on tests/functional_tests/ffront_tests/test_foast_parsing.py
> +from functional.type_system import type_specifications as ts
```suggestion
from functional.ffront.type_system import type_specifications as ts
```

2022-12-20 14:36 UTC, tehrengruber commented on tests/functional_tests/ffront_tests/test_past_parsing.py
> +from functional.type_system import type_specifications as ts
```suggestion
from functional.ffront.type_system import type_specifications as ts
```

2022-12-20 14:36 UTC, tehrengruber commented on tests/functional_tests/ffront_tests/test_math_builtin_execution.py
> +from functional.type_system import type_specifications as ts, type_translation
```suggestion
from functional.ffront.type_system import type_specifications as ts
from functional.type_system import type_translation
```

2022-12-21 09:53 UTC, petiaccja commented on setup.cfg
>  ignore_errors = True
```
src/functional/ffront/foast_passes/type_deduction.py:106:9: error: Unsupported right operand type for in ("Union[List[Dimension], ellipsis]")  [operator]
src/functional/ffront/foast_passes/type_deduction.py:106:45: error: Item "ellipsis" of "Union[List[Dimension], ellipsis]" has no attribute "__iter__" (not iterable)  [union-attr]
src/functional/ffront/foast_passes/type_deduction.py:177:83: error: Argument "returns" to "FunctionType" has incompatible type "TypeSpec"; expected "Union[DataType, DeferredType, VoidType]"  [arg-type]
src/functional/ffront/foast_passes/type_deduction.py:642:12: error: Unsupported right operand type for in ("Union[List[Dimension], ellipsis]")  [operator]
src/functional/ffront/foast_passes/type_deduction.py:643:60: error: Item "ellipsis" of "Union[List[Dimension], ellipsis]" has no attribute "__iter__" (not iterable)  [union-attr]
src/functional/ffront/foast_passes/type_deduction.py:651:34: error: Item "ellipsis" of "Union[List[Dimension], ellipsis]" has no attribute "__iter__" (not iterable)  [union-attr]
```

2022-12-21 10:00 UTC, petiaccja commented on src/functional/ffront/dialect_ast_enums.py
> +from eve import StrEnum
Done

2022-12-21 10:08 UTC, petiaccja commented on src/functional/ffront/past_passes/closure_var_type_deduction.py
> +                    type=from_value(self.closure_vars[sym.id]),
Done

2022-12-21 10:58 UTC, petiaccja commented on src/functional/ffront/type_info.py
> +]
Flake8 complains about unused imports.

2022-12-21 12:03 UTC, petiaccja commented on src/functional/ffront/type_translation.py
> +__all__ = ["get_scalar_kind", "from_type_hint", "from_value"]
Not at the moment, so in essence, I can remove this. I have some ideas to replace `__gt_type__` with a non-intrusive but still extensible alternative, and that would eventually relocate the handling of field view types to this file.

2022-12-21 16:01 UTC, petiaccja commented on src/functional/ffront/decorator.py
> +import functional.ffront.dialect_ast_enums as ast_enums
Done

2022-12-22 15:30 UTC, tehrengruber approved these changes

2022-12-22 15:30 UTC, merged