Add support for positional-or-keyword arguments
GridTools/gt4py pull request #1248
Opened 2023-05-01 07:58 UTC by tehrengruber

Description to follow

2023-05-23 12:54 UTC, DropD requested changes
Just a couple of small things.

2023-05-23 12:54 UTC, DropD commented on src/gt4py/next/ffront/type_info.py
> +    )
You might consider shortening this to

```suggestion
@type_info.canonicalize_arguments.register(ts_ffront.FieldOperatorType)
@type_info.canonicalize_arguments.register(ts_ffront.ProgramType)
def canonicalize_program_arguments(
    gt_callable_type: ts_ffront.ProgramType | ts_ffront.FieldOperatorType,
    args: tuple | list,
    kwargs: dict,
    *,
    ignore_errors=False,
    use_signature_ordering=False,
) -> tuple[list, dict]:
    return type_info.canonicalize_arguments(
        gt_callable_type.definition,
        args,
        kwargs,
        ignore_errors=ignore_errors,
        use_signature_ordering=use_signature_ordering,
    )
```

2023-05-23 12:54 UTC, DropD commented on src/gt4py/next/ffront/type_info.py
> +def _scan_param_promotion(param: ts.TypeSpec, arg: ts.TypeSpec):
missing return type annotation

2023-05-23 12:54 UTC, DropD commented on src/gt4py/next/type_system/type_info.py
> +def canonicalize_function_arguments(
I didn't look at this function in any detail

2023-05-23 12:54 UTC, DropD commented on src/gt4py/next/type_system/type_info.py
> +def structural_function_signature_incompatibilities(
I didn't look at this function in detail

2023-05-23 12:54 UTC, DropD commented on src/gt4py/next/type_system/type_info.py
> +def function_signature_incompatibilities_func(  # noqa: C901
I didn't look at this in detail either.

2023-05-23 12:54 UTC, DropD commented on src/gt4py/next/ffront/type_info.py
>  def function_signature_incompatibilities_scanop(
Didn't have time to look at the function body here.

2023-05-23 12:54 UTC, DropD commented on tests/next_tests/integration_tests/feature_tests/ffront_tests/test_execution.py
> +def test_interface_kwargs(fieldview_backend):
Should use the `cartesian_case` fixture and `allocate`/`verify` instead of the old `fieldview_backend`

2023-05-23 12:54 UTC, DropD commented on tests/next_tests/integration_tests/feature_tests/ffront_tests/test_type_deduction.py
> +# TODO
Empty TODO comment

2023-05-23 14:37 UTC, DropD commented
From Conversation earlier:
- Some apparent complexity in the type info functions comes from collecting error messages. If it was more explicit that this is what's happening, it would help readability.

2023-05-24 19:50 UTC, tehrengruber commented
As mentioned by @DropD understanding the details of the algorithms in `type_info` in this PR (i.e. `canonicalize_function_arguments`, `structural_function_signature_incompatibilities`, `function_signature_incompatibilities_func`) is very hard and time consuming. I decomposed it into as many functions that still have meaning as a unit of their own as possible, but after all a rich call interface results in a complex algorithm. I further increased the test coverage (both unit and integration tests) so the review doesn't need to go into each and every detail.

@egparedes This PR is not time critical at all. While it is touching many files, the parts it is touching are rarely changed or the changes there are minor. Review whenever you like.

2023-06-19 12:36 UTC, DropD approved these changes

2023-06-20 07:21 UTC, merged