feature[next]: Save type to annex in ITIR type inference
GridTools/gt4py pull request #1259
Opened 2023-05-30 10:12 UTC by tehrengruber

This PR allows saving the results of type inference in the ITIR nodes. This is particularly useful for passes that modify the tree, but need type information during the process (in my case this is for the temporary extraction pass).

```python
testee = im.lambda_("a")(im.plus("a", im.literal("1", "float32")))
ti.infer(testee, save_to_annex=True)
param_type = testee.params[0].annex.type
assert isinstance(param_type, ti.Val) and param_type.dtype.name == "float32"
```

2023-05-31 15:50 UTC, egparedes requested changes
Just a couple of minor issues and it's ready to go.

2023-05-31 15:50 UTC, egparedes commented on src/gt4py/next/iterator/type_inference.py
> +def _save_types_to_annex(node, types):
Missing typing annotations

2023-05-31 15:50 UTC, egparedes commented on src/gt4py/next/iterator/type_inference.py
> +                )
```suggestion
                raise AssertionError(
                    f"Expected a type to be inferred for node `{child_node}`, but none was found."
                )
```

2023-06-01 08:51 UTC, egparedes approved these changes
It looks good to me.

2023-06-06 09:44 UTC, tehrengruber commented on src/gt4py/next/iterator/type_inference.py
> +    return dictionary is not enough.
```suggestion
    The `save_to_annex` flag should only be used as a last resort when the  return dictionary is
    not enough.
```

2023-06-06 11:03 UTC, merged