test:[cartesian]: update hypothesis and fix the health check issues found in daily CI
GridTools/gt4py pull request #1333
Opened 2023-09-06 12:55 UTC by DropD

## Description

The daily CI [found](https://github.com/GridTools/gt4py/actions/runs/6092626057/job/16531045858#step:8:2297) that after updating to hypothesis 6.82.1 some tests in cartesian are failing hypothesis health checks. This PR tries to fix that.

## Requirements

- [X] All fixes and/or new features come with corresponding tests.
- [X] Important design decisions have been documented in the approriate ADR inside the [docs/development/ADRs/](docs/development/ADRs/Index.md) folder.

2023-09-06 13:29 UTC, DropD commented
Seems that the new version caused the health check for multiple executers to trigger on parametrized tests. From the tests in hypothesis itself it looked like this might not happen if parametrization is the outer decorator (applied after @given).

2023-09-06 13:41 UTC, egparedes approved these changes
It looks good to me.

2023-09-07 08:11 UTC, egparedes requested changes
We need to run the requirements update workflow before merging.

2023-09-07 08:11 UTC, egparedes commented on requirements-dev.in
> -hypothesis>=6.0.0
Whenever any requirement is modified, the tox workflow updating all config files need to be executed as explained here: https://github.com/GridTools/gt4py/blob/main/docs/development/tools/requirements.md

2023-09-12 13:46 UTC, egparedes commented on .pre-commit-config.yaml
>    rev: v1.5.0  # MUST match version ^^^^ in constraints.txt (if the mirror is up-to-date)
```suggestion
  rev: v1.5.1  # MUST match version ^^^^ in constraints.txt (if the mirror is up-to-date)
```

2023-09-12 13:49 UTC, egparedes approved these changes
The mypy version in pre-commit-config needs to be updated  manually because the hook is defined in the mirror repository and it's not always up-to-date.

This has been now fixed so the PR is ready to be merged IMHO.

It looks good to me

2023-09-19 07:09 UTC, merged