feat[next]: DaCe support for neighbor strided offset
GridTools/gt4py pull request #1344
Opened 2023-09-29 08:05 UTC by edopao

## Description

Neighbor strided offset is another ITIR feature needed in DaCe backend in order to support icon4py stencils. This PR proposes an implementation based on map range with step, corresponding to the offset stride.

## Requirements

2023-10-13 09:36 UTC, petiaccja reviewed
To do: choose how to represent max_neighbors:
- Runtime: extract from `StridedNeighborOffsetProvider` instance and pass it as an SDFG symbol (simple and independent of caching SDFGs)
- Compile time: extract from `StridedNeighborOffsetProvider` instance and hardcode it in the SDFG (error prone when caching SDFGs)
- Compile time: create and infer a `StridedNeighborOffsetProviderType` from the instance and hardcode from the `Type` (lots of work but great for caching SDFGs)

2023-10-16 10:00 UTC, edopao commented
Decided to go for option 2 to represent `max_neighbors`:
- Compile time: extract from `StridedNeighborOffsetProvider` instance and hardcode it in the SDFG (error prone when caching SDFGs)

The reason is that this option provides several advantages:
- It is compatible with the long-term more desirable solution to create and infer a `StridedNeighborOffsetProviderType`
- It enables compile-time optimizations
- This solution is already used to select the scan dimension (`column_axis`)

2023-10-16 15:00 UTC, petiaccja requested changes
Just a small thing with your caching.

2023-10-16 15:00 UTC, petiaccja commented on src/gt4py/next/program_processors/runners/dace_iterator/__init__.py
> +    ]
Just drop the ones that don't have any compile-time properties. The ones with only runtime properties should manifest in the SDFG structure, that should be enough, right? Let me know if I'm missing something here.
```suggestion
    max_neighbors = [
        (k, v.max_neighbors)
        for k, v in offset_provider.items()
        if isinstance(v, (NeighborTableOffsetProvider, StridedNeighborOffsetProvider))
    ]
```

2023-10-16 15:00 UTC, petiaccja commented on src/gt4py/next/program_processors/runners/dace_iterator/__init__.py
> +    return m.hexdigest()
Looks good. I hope it runs faster than the SDFG generation :P

2023-10-17 08:06 UTC, petiaccja approved these changes

2023-10-17 08:11 UTC, merged