feat[next][dace]: Add more debug info to DaCe
GridTools/gt4py pull request #1384
Opened 2023-12-04 09:40 UTC by kotsaloscv

## Description

Add more debug info to DaCe (pass SourceLocation from past/foast to itir, and from itir to the SDFG)

2023-12-04 10:33 UTC, petiaccja requested changes
The PR is pretty straightforward (that's a good thing), I left a few comments, but other than that I think there isn't much to change.

However, one thing I'm really missing is tests or any way to ensure that location info is properly transmitted. For example, if someone writes a new iterator IR pass and they don't pass the location, we won't know until somebody tries to look at the generated SDFGs while doing something else. That may be weeks or months down the line and finding the culprit causing the loss of location info will be difficult and annoying.

If you make the location field mandatory in iterator IR, that would do the trick. You could also enforce that location is not None in the SDFG generation, though that's less clear. You could also add a test that verifies if the SDFG has debug info.

2023-12-05 13:41 UTC, kotsaloscv commented
> The PR is pretty straightforward (that's a good thing), I left a few comments, but other than that I think there isn't much to change.
> 
> However, one thing I'm really missing is tests or any way to ensure that location info is properly transmitted. For example, if someone writes a new iterator IR pass and they don't pass the location, we won't know until somebody tries to look at the generated SDFGs while doing something else. That may be weeks or months down the line and finding the culprit causing the loss of location info will be difficult and annoying.
> 
> If you make the location field mandatory in iterator IR, that would do the trick. You could also enforce that location is not None in the SDFG generation, though that's less clear. You could also add a test that verifies if the SDFG has debug info.

FYI, I have integrated Peter's comments in my PR.
I also experimented on making the SourceLocation a mandatory field in the itir node, but it turns out that we will have to modify the code in countless places. There are so many tests that experiment with itir nodes for which we will have to pass a valid location. I do not think that it worths the investment. As is right now, I find it less intrusive and it is up to us to decide what we want to pass from past/foast to itir.
Regarding the testing of the genereted sdfgs to have a valid bebuginfo field, I have added this check in the code:
https://github.com/kotsaloscv/gt4py/blob/more_debinfo/src/gt4py/next/program_processors/runners/dace_iterator/__init__.py#L222
At least, the developer will always be warned about this field and add it appropriately.

cc: @havogt @tehrengruber

2024-01-04 11:48 UTC, petiaccja commented on src/gt4py/next/program_processors/runners/dace_iterator/utility.py
> +    return di
Simplify control flow:
```suggestion
    if location:
        return dace.dtypes.DebugInfo(
            start_line=location.line,
            start_column=location.column if location.column else 0,
            end_line=location.end_line if location.end_line else -1,
            end_column=location.end_column if location.end_column else 0,
            filename=location.filename,
        )
    return debuginfo
```

2024-01-04 16:24 UTC, tehrengruber commented on src/gt4py/eve/traits.py
> +        return result
```suggestion
```
Beside the code duplication I don't think this is needed. Just inheriting from `PreserveLocation` should be fine right?

2024-01-04 16:24 UTC, tehrengruber commented on src/gt4py/eve/visitors.py
> +class PreserveLocation(NodeVisitor):
```suggestion
class PreserveLocationVisitor(NodeVisitor):
```

2024-01-04 16:24 UTC, tehrengruber commented on src/gt4py/next/ffront/foast_to_itir.py
> +            and self.preserve_location
Why is the location preservation disabled for `foast.Name` nodes?
```suggestion
            and not isinstance(node, foast.Name)
            and self.preserve_location
```
If this wouldn't be needed the `preserve_location` flag could easily be added to `PreserveLocation` class making this custom handling unneeded.

2024-01-04 16:24 UTC, tehrengruber commented on src/gt4py/next/ffront/past_to_itir.py
> +            fun=itir.SymRef(id=domain_builtin), args=domain_args, location=out_field.location
Such that the location of the `node_domain` is used when available.
```suggestion
            fun=itir.SymRef(id=domain_builtin), args=domain_args, location=(node_domain or out_field).location
```

2024-01-04 16:24 UTC, tehrengruber commented on src/gt4py/next/ffront/past_to_itir.py
> +        itir_node = [self.visit(bound) for bound in node_domain.values_[dim_i].elts]
Why is not taken care of by the `PreserveLocationWithSymbolTableTrait`? Aren't you just manually copying the location of the bound you are also visiting?

2024-01-23 15:05 UTC, tehrengruber approved these changes
Changes as discussed in person.

2024-01-23 17:13 UTC, merged