feat[dace]: Buildflags to the `ITIR -> SDFG` translation
GridTools/gt4py pull request #1389
Opened 2023-12-08 15:01 UTC by philip-paul-mueller

It makes it possible to pass build flags to the `run_dace_iterator` arguments.

2023-12-11 08:22 UTC, edopao approved these changes

2023-12-11 08:28 UTC, edopao commented
cscs-ci run

2023-12-14 13:51 UTC, edopao commented on src/gt4py/next/program_processors/runners/dace_iterator/__init__.py
> +        build_args=_cpu_args,
I propose to move the definition of `_cpu_args` inside this function (`_run_dace_cpu`).

I also propose this modification to its definition:
```
compiler_args = dace.config.Config.get("compiler", "cpu", "args")
# disable finite-math-only in order to support isfinite/isinf/isnan builtins
if "-ffast-math" in compiler_args:
    compiler_args += " -fno-finite-math-only"
if "-ffinite-math-only" in compiler_args:
    compiler_args.replace("-ffinite-math-only", "")
```

2023-12-14 13:54 UTC, edopao requested changes

2023-12-14 13:54 UTC, edopao commented on src/gt4py/next/program_processors/runners/dace_iterator/__init__.py
> +        build_args=_cpu_args,
I propose to move the definition of `_cpu_args` inside this function (`_run_dace_cpu`).

I also propose this modification to its definition:
```
compiler_args = dace.config.Config.get("compiler", "cpu", "args")
# disable finite-math-only in order to support isfinite/isinf/isnan builtins
if "-ffast-math" in compiler_args:
    compiler_args += " -fno-finite-math-only"
if "-ffinite-math-only" in compiler_args:
    compiler_args.replace("-ffinite-math-only", "")
```

2023-12-18 08:42 UTC, philip-paul-mueller commented
cscs-ci run

2023-12-18 08:48 UTC, edopao approved these changes

2023-12-18 09:58 UTC, merged