ruff implementation
GridTools/gt4py pull request #1466
Opened 2024-02-22 13:20 UTC by nfarabullini

2024-02-26 16:08 UTC, egparedes requested changes
Here is the first round of feedback. Didn't have time to review all the changes yet but I'll do in the second pass, once this comments and the merge conflicts are fixed.

2024-02-26 16:08 UTC, egparedes commented on src/gt4py/eve/datamodels/core.py
> +    """  # doctest conventions confuse RST validator
Remove unneeded comment for previously existing `#noqa` code

2024-02-26 16:08 UTC, egparedes commented on src/gt4py/eve/datamodels/core.py
> +    """  # sphinx.napoleon conventions confuse RST validator
Remove unneeded comment for previously existing `#noqa` code

2024-02-26 16:08 UTC, egparedes commented on src/gt4py/eve/datamodels/core.py
> +    """  # doctest conventions confuse RST validator
Remove unneeded comment for previously existing `#noqa` code

2024-02-26 16:08 UTC, egparedes commented on src/gt4py/eve/datamodels/core.py
> +def _make_datamodel(  # too complex but still readable and documented
Remove unneeded comment for previously existing `#noqa` code

2024-02-26 16:08 UTC, egparedes commented on src/gt4py/eve/extended_typing.py
> +    def __get__(  # redefinion of unused member
Remove unneeded comment for previously existing `#noqa` code

2024-02-26 16:08 UTC, egparedes commented on src/gt4py/eve/extended_typing.py
> +    def __get__(  # redefinion of unused member
Remove unneeded comment for previously existing `#noqa` code

2024-02-26 16:08 UTC, egparedes commented on src/gt4py/eve/extended_typing.py
> +def extended_runtime_checkable(  # too complex but unavoidable
Remove unneeded comment for previously existing `#noqa` code

2024-02-26 16:08 UTC, egparedes commented on src/gt4py/eve/extended_typing.py
> +def infer_type(  # function is complex but well organized in independent cases
Remove unneeded comment for previously existing `#noqa` code

2024-02-26 16:08 UTC, egparedes commented on src/gt4py/eve/type_definitions.py
> +from enum import Enum as Enum, IntEnum as IntEnum  # imported but unused
Remove unneeded comment for previously existing `#noqa` code

2024-02-26 16:08 UTC, egparedes commented on src/gt4py/eve/type_definitions.py
> +class FrozenList(Tuple[_Tc, ...], metaclass=abc.ABCMeta):  # no abstract methods
Remove unneeded comment for previously existing `#noqa` code

2024-02-26 16:08 UTC, egparedes commented on src/gt4py/eve/type_validation.py
> +    def __call__(  # redefinion of unused member
Remove unneeded comment for previously existing `#noqa` code

2024-02-26 16:08 UTC, egparedes commented on src/gt4py/eve/type_validation.py
> +    def __call__(  # redefinion of unused member
Remove unneeded comment for previously existing `#noqa` code

2024-02-26 16:08 UTC, egparedes commented on src/gt4py/eve/type_validation.py
> +    def __call__(  # redefinion of unused member
Remove unneeded comment for previously existing `#noqa` code

2024-02-26 16:08 UTC, egparedes commented on src/gt4py/eve/type_validation.py
> +    def __call__(  # redefinion of unused member / complex but well organized in cases
Remove unneeded comment for previously existing `#noqa` code

2024-02-26 16:08 UTC, egparedes commented on src/gt4py/next/common.py
> +    def __getitem__(self, index: slice) -> UnitRange:  # redefine unused
Remove unneeded comment for previously existing `#noqa` code

2024-02-26 16:08 UTC, egparedes commented on src/gt4py/next/common.py
> +    def __getitem__(self, index: int | slice) -> int | UnitRange:  # redefine unused
Remove unneeded comment for previously existing `#noqa` code

2024-02-26 16:08 UTC, egparedes commented on src/gt4py/next/common.py
> +    def __getitem__(self, index: slice) -> Self:  # redefine unused
Remove unneeded comment for previously existing `#noqa` code

2024-02-26 16:08 UTC, egparedes commented on src/gt4py/next/common.py
> +    def __getitem__(  # redefine unused
Remove unneeded comment for previously existing `#noqa` code

2024-02-26 16:08 UTC, egparedes commented on src/gt4py/next/common.py
> +    def __getitem__(  # redefine unused
Remove unneeded comment for previously existing `#noqa` code

2024-02-26 16:08 UTC, egparedes commented on src/gt4py/next/common.py
> +    ) -> NamedRange | Domain:  # redefine unused
Remove unneeded comment for previously existing `#noqa` code

2024-02-26 16:08 UTC, egparedes commented on src/gt4py/next/embedded/operators.py
> +    ) -> common.Field:  # we cannot properly type annotate relative to self.fun
Remove unneeded comment for previously existing `#noqa` code

2024-02-26 16:08 UTC, egparedes commented on src/gt4py/next/ffront/field_operator_ast.py
> +    type: Union[SymbolT, ts.DeferredType]  # A003
Remove unneeded comment for previously existing `#noqa` code

2024-02-26 16:08 UTC, egparedes commented on src/gt4py/next/ffront/field_operator_ast.py
> +    id: Coerced[SymbolRef]  # shadowing a python builtin
Remove unneeded comment for previously existing `#noqa` code

2024-02-26 16:08 UTC, egparedes commented on src/gt4py/next/ffront/field_operator_ast.py
> +    id: Union[FieldSymbol, TupleSymbol, ScalarSymbol]  # shadowing a python builtin
Remove unneeded comment for previously existing `#noqa` code

2024-02-26 16:08 UTC, egparedes commented on src/gt4py/next/ffront/field_operator_ast.py
> +    id: Coerced[SymbolName]  # shadowing a python builtin
Remove unneeded comment for previously existing `#noqa` code

2024-02-26 16:08 UTC, egparedes commented on src/gt4py/next/ffront/field_operator_ast.py
> +    id: Coerced[SymbolName]  # shadowing a python builtin
Remove unneeded comment for previously existing `#noqa` code

2024-02-26 16:08 UTC, egparedes commented on src/gt4py/next/ffront/field_operator_ast.py
> +    type: Union[ts_ffront.FieldOperatorType, ts.DeferredType] = ts.DeferredType(
Remove unneeded comment for previously existing `#noqa` code

2024-02-26 16:08 UTC, egparedes commented on src/gt4py/next/ffront/field_operator_ast.py
> +    id: Coerced[SymbolName]  # shadowing a python builtin
Remove unneeded comment for previously existing `#noqa` code

2024-02-26 16:08 UTC, egparedes commented on src/gt4py/next/ffront/field_operator_ast.py
> +    type: Union[ts_ffront.ScanOperatorType, ts.DeferredType] = ts.DeferredType(
Remove unneeded comment for previously existing `#noqa` code

2024-02-27 08:08 UTC, nfarabullini commented on .pre-commit-config.yaml
> +    exclude: |-
no idea

2024-02-28 10:36 UTC, nfarabullini commented on src/gt4py/next/program_processors/runners/dace_iterator/__init__.py
> +                getframeinfo(currentframe()),  # type: ignore
can you add here what type ignore it is?

2024-02-28 14:56 UTC, egparedes approved these changes
It looks great. Thanks for all the work!

2024-02-28 14:58 UTC, merged