feat[cartesian]: Specify compiler optimization level and flags via env variables
GridTools/gt4py pull request #1491
Opened 2024-03-14 13:03 UTC by stubbiali

## Description

This PR allows downstream applications to specify compiler optimization level and flags on a stencil basis.

## Requirements

- [ ] All fixes and/or new features come with corresponding tests.
- [ ] Important design decisions have been documented in the approriate ADR inside the [docs/development/ADRs/](docs/development/ADRs/Index.md) folder.

If this PR contains code authored by new contributors please make sure:

- [ ] All the authors are covered by a valid contributor assignment agreement provided to ETH Zurich and signed by the employer if needed.
- [ ] The PR contains an updated version of the `AUTHORS.md` file adding the names of all the new contributors.

2024-03-19 16:07 UTC, havogt requested changes
Please add a test that illustrates using the feature. Not sure if removing `debug_mode` is a good idea.

2024-03-19 16:08 UTC, havogt commented
Adding @egparedes and @FlorianDeconinck for more opinions.

2024-03-20 14:08 UTC, FlorianDeconinck approved these changes
LGTM

2024-03-20 14:20 UTC, stubbiali commented on src/gt4py/cartesian/backend/pyext_builder.py
> +    mode_flags = [f"-O{opt_level}", "-DNDEBUG", *extra_opt_flags.split()]
@havogt On (my) mac, the flag `-DNDEBUG` is required to make compilation works with any optimization level, so I hardcoded it into `mode_flags` for the sake of convenience. If you prefer, we could be more flexible: 
```suggestion
    mode_flags = [f"-O{opt_level}"]
    if extra_opt_flags != "":
        mode_flags += [*extra_opt_flags.split()]
    elif opt_level == "0":
        mode_flags.append("-ggdb")
    else:
        mode_flags.append("-DNDEBUG")
```

2024-03-20 16:53 UTC, havogt commented on src/gt4py/cartesian/backend/pyext_builder.py
> +    opt_level: Literal["0", "1", "2", "3", "s"] = "3",
Semantically I would do the following:
```suggestion
    opt_level: Literal["0", "1", "2", "3", "s"] = "3" if not debug_mode else "0",
```
I.e. keep the old behavior for `debug_mode`, but if you use additionally the opt_level, then overwrite the default opt_level.

2024-05-24 08:48 UTC, havogt commented on src/gt4py/cartesian/backend/pyext_builder.py
> +        ["-O0", "-ggdb"] if debug_mode else [f"-O{opt_level}", "-DNDEBUG", *extra_opt_flags.split()]
this fixes my comment above

2024-06-17 18:24 UTC, havogt approved these changes

2024-06-25 09:58 UTC, havogt commented
cscs-ci run

2024-06-25 18:25 UTC, merged