feat[cartesian]: gtc `cuda` backend deprecation
GridTools/gt4py pull request #1498
Opened 2024-03-15 15:31 UTC by FlorianDeconinck

## Description

GTC `cuda` backend was made available a few years ago for AI2 team research. It has been kept updated but a recent poll shows that it is not in use. Recent new features break the backend and we propose here to hard deprecate it rather than keep spending time maintaining it.

`GT4PY_GTC_CUDA_USE=1` can be used to force the use of the backend, but will warn that any feature from February 2024 are not available/not tested.

## Requirements

- [ ] All fixes and/or new features come with corresponding tests.
- [ ] Important design decisions have been documented in the approriate ADR inside the [docs/development/ADRs/](docs/development/ADRs/Index.md) folder.

2024-03-19 16:03 UTC, havogt reviewed
Looks good to me. Will assign @egparedes if he has any concerns with this pattern.

2024-03-19 16:03 UTC, havogt commented on src/gt4py/cartesian/config.py
> +# Deerecate by default the gtc `cuda` backend. Use GT4PY_GTC_CUDA_USE=1 to turn it on
```suggestion
# Deprecate by default the gtc `cuda` backend. Use GT4PY_GTC_CUDA_USE=1 to turn it on
```

2024-03-20 16:25 UTC, havogt commented on src/gt4py/cartesian/backend/cuda_backend.py
> +                "cuda backend is deprecated, feature developed after February 2024 will not be available",
```suggestion
                "The 'cuda' backend is deprecated, features developed after February 2024 will not be available",
```

2024-03-20 16:25 UTC, havogt commented on src/gt4py/cartesian/backend/cuda_backend.py
> +                "cuda backend is no longer maintained (February 2024)."
```suggestion
                "The 'cuda' backend is no longer maintained (February 2024)."
```

2024-03-20 17:38 UTC, egparedes reviewed
I'm fine with the changes although I find the `deprecated` attribute added to backend a bit invasive and ad hoc.

Another alternative could be to add a generic list of deprecated backends in the `cartesian.config` like:

```python
DEPRECATED_BACKENDS: Dict[str, bool] = {
    name: bool(int(os.environ.get(f"GT4PY_GTC_ENABLE_{name.upper()}", "0")))
    for name in ["cuda"]
}
```
and then check this setting when accessing the backend registry in `cartesian.backend.base.py`:

```python
def from_name(name: str) -> Optional[Type["Backend"]]:
    if name in config.DEPRECATED_BACKENDS:
        if not config.DEPRECATED_BACKENDS[name]:
            raise NotImplementedError(
                f"The '{name}' backend is no longer maintained."
                "You can still force the use of the backend by defining GT4PY_GTC_CUDA_USE=1."
            )

        warnings.warn(
            f"The '{name}' backend is deprecated, new features developed after deprecation are not available",
            DeprecationWarning,
            stacklevel=2,
        )

    return REGISTRY.get(name, None)
```
But it's just an idea, I'm fine with other alternatives or the current implementation.

2024-03-20 18:02 UTC, FlorianDeconinck commented
> I'm fine with the changes although I find the `deprecated` attribute added to backend a bit invasive and ad hoc.
> 
> Another alternative could be to add a generic list of deprecated backends in the `cartesian.config.py` module like:
> 
> ```python
> DEPRECATED_BACKENDS: Dict[str, bool] = {
>     name: bool(int(os.environ.get(f"GT4PY_GTC_ENABLE_{name.upper()}", "0")))
>     for name in ["cuda"]
> }
> ```
> 
> and then check this setting when accessing the backend registry in `cartesian.backend.base.py`:
> 
> ```python
> def from_name(name: str) -> Optional[Type["Backend"]]:
>     if name in config.DEPRECATED_BACKENDS:
>         if not config.DEPRECATED_BACKENDS[name]:
>             raise NotImplementedError(
>                 f"The '{name}' backend is no longer maintained."
>                 "You can still force the use of the backend by defining GT4PY_GTC_CUDA_USE=1."
>             )
> 
>         warnings.warn(
>             f"The '{name}' backend is deprecated, new features developed after deprecation are not available",
>             DeprecationWarning,
>             stacklevel=2,
>         )
> 
>     return REGISTRY.get(name, None)
> ```
> 
> But it's just an idea, I'm fine with other alternatives or the current implementation.

I don't have strong feelings. I opted for a flag directly in `CUDABackend` so it's visible there. But I could go either way considering the warning remains. @havogt ?

2024-04-02 21:22 UTC, egparedes commented
@FlorianDeconinck , I had another idea about how to implement the deprecation mechanism using an intermediate approach between your proposal and mine, which I think takes the best from both options. You can see untested/pseudo-code below, what do you think?

```python
##### cartesian/config.py

#: Deprecated backends register themselves here as enabled (`True`) or
#: disabled (`False`) based on explicit user settings communicated via
#: 'GT4PY_ENABLE_GTC_{backend_name}' environment variables.
DEPRECATED_BACKENDS: Dict[str, bool] = {}

##### cartesian/backend/base.py

def deprecate(message: str) -> Callable[[Type[Backend]], Type[Backend]]:
    def  _decorator(backend: Type[Backend]) -> Type[Backend]:
        original_generate = backend.generate
        forced_enable = bool(int(os.environ.get(f"GT4PY_GTC_ENABLE_{backend.name.upper()}", "0")))
        gt_config.DEPRECATED_BACKENDS[backend.name] = forced_enable
        
        # We push for hard deprecation here by raising by default and warning if enabling has been forced.
        if forced_enable:
            def _generate(self) -> Type["StencilObject"]:
                warnings.warn(
                    f"The '{self.name}' backend is deprecated: f{message}",
                    DeprecationWarning,
                    stacklevel=2,
                )
                original_generate(self)
        else:
            def _generate(self) -> Type["StencilObject"]:
                   raise NotImplementedError(
                        f"The '{self.name}' backend is deprecated: f{message}\n",
                        f"You can still force the use of the backend by defining GT4PY_ENABLE_GTC_{self.name}=1."
                    )
        
        backend.generate = functools.wraps(original_generate)(_generate)
        return backend

    return _decorator

##### cartesian/backend/cuda_backend.py

@deprecate("new features developed after February 2024 are not available.")
@register
class CudaBackend(BaseGTBackend, CLIBackendMixin):
    ...

```
@havogt any opinions? We should try to agree on something quickly and get this merged as soon as possible.

2024-04-09 09:28 UTC, egparedes commented
> That's much more pythonic, I like it. 

Indeed. I just found out that Python 3.13 adds a very similar [`deprecated()`](https://docs.python.org/3.13/library/warnings.html#warnings.deprecated) function to the standard library. Since it is already available in the `typing_extensions` package, there is a even simpler way to implement this PR:

```python
##### cartesian/backend/base.py
from typing_extensions import deprecated

BackendT = TypeVar("BackendT", bound=Type[Backend])

def disabled(message: str, *, enabled_env_var: str) -> Callable[[BackendT], BackendT]:
    # We push for hard deprecation here by raising by default and warning if enabling has been forced.
    enabled = bool(int(os.environ.get(enable_env_var, "0")))
    if enabled:
        return deprecated(message)
    else:
        def _decorator(cls: BackendT) -> BackendT:
            def _new(cls, *args, **kwargs) -> Never:
                raise NotImplementedError(
                    f"Disabled '{cls.name}' backend: 'f{message}'\n",
                    f"You can still enable the backend by hand using the environment variable '{enabled_env_var}=1'"
                )
            
            cls.new = _new
            return cls

    
        return _decorator

##### cartesian/backend/cuda_backend.py
@disabled(
    "CUDA backend is deprecated. New features developed after February 2024 are not available.",
    enabled_env_var="GT4PY_GTC_ENABLE_CUDA"
)
@register
class CudaBackend(BaseGTBackend, CLIBackendMixin):
    ...
    
```

2024-04-22 16:59 UTC, FlorianDeconinck commented
@egparedes 

Finally some time to come back to this. I swapped for that solution, I had to do some fiddling for the type hint and some ignores for `mypy`. The other change is that I swap the `generate` function call to a function that `raise` and I add a `disabled` member on the class so I can do detection for unit test (which was kind of the intent to begin with)

2024-04-25 15:34 UTC, egparedes requested changes
Some comments about type hints that I think are wrong and a couple of minor style suggestions, but overall it's ready. I'll approve as soon as my comments are addressed.

2024-04-25 15:34 UTC, egparedes commented on src/gt4py/cartesian/backend/base.py
> +def disabled(message: str, *, enabled_env_var: str) -> Callable[[Backend], Backend]:
```suggestion
def disabled(message: str, *, enabled_env_var: str) -> Callable[[Type[Backend]], Type[Backend]]:
```

2024-04-25 15:34 UTC, egparedes commented on src/gt4py/cartesian/backend/base.py
> +        def _decorator(cls: Backend) -> Backend:
```suggestion
        def _decorator(cls: Type[Backend]) -> Type[Backend]:
```

2024-04-25 15:34 UTC, egparedes commented on tests/cartesian_tests/definitions.py
> +        if not hasattr(backend, "disabled") or not backend.disabled:
```suggestion
        if not getattr(backend, "disabled", False):
```

2024-04-25 16:15 UTC, FlorianDeconinck commented
Merged all comments in one commit, thanks!

2024-04-26 08:12 UTC, egparedes approved these changes
It looks good to me.

2024-04-26 13:22 UTC, merged