feat[next]: Optimisations for icon4py
GridTools/gt4py pull request #1536
Opened 2024-04-22 10:38 UTC by samkellerhals

## Description

Changes to reduce Python overhead when calling icon4py granules from ICON.

- Removing `isinstance` checks from `extract_connectivity_args` and `convert_args`.

2024-04-22 11:56 UTC, havogt commented on src/gt4py/next/program_processors/runners/gtfn.py
> +            args.append(result)
all this stuff could be cached to remove the overhead completely

2024-05-06 13:00 UTC, havogt requested changes
Forwarding the review to @egparedes for improving Python patterns in performance critical code parts.

2024-05-06 13:01 UTC, havogt commented
But in general, could make sense to discuss this in the context of going towards _frozen_ programs.

2024-05-06 13:02 UTC, havogt commented on src/gt4py/next/iterator/embedded.py
> -    warnings.warn("`np_as_located_field()` is deprecated, use `gtx.as_field()`", DeprecationWarning)  # noqa: B028 [no-explicit-stacklevel]
I see it was intentional. Still should be undone and fixed on the icon4py side.

2024-05-07 07:35 UTC, samkellerhals commented on src/gt4py/next/iterator/embedded.py
> -    warnings.warn("`np_as_located_field()` is deprecated, use `gtx.as_field()`", DeprecationWarning)  # noqa: B028 [no-explicit-stacklevel]
So basically emitting the warning was slowing things down on the icon4py side when creating the gt4py fields when calling the granule. In what way could this be fixed on the icon4py side?

2024-05-07 07:40 UTC, samkellerhals commented on src/gt4py/next/program_processors/runners/gtfn.py
> +type_handlers_convert_args = {
I think it could work, but my feeling is that it would be slower than a simple dictionary lookup.

2024-05-07 12:43 UTC, havogt commented on src/gt4py/next/iterator/embedded.py
> -    warnings.warn("`np_as_located_field()` is deprecated, use `gtx.as_field()`", DeprecationWarning)  # noqa: B028 [no-explicit-stacklevel]
Ok, I see, then it probably makes sense to use (temporarily) the `common._field()` function to wrap an array into a field.

2024-05-16 07:08 UTC, DropD commented on src/gt4py/next/program_processors/runners/gtfn.py
> +type_handlers_convert_args = {
I think it would be preferable to sacrifice readability only on the basis of hard evidence.

2024-05-16 07:11 UTC, DropD commented on src/gt4py/next/program_processors/runners/gtfn.py
> +
Once I get size args extraction moved to this stage, I will look into adding that.

2024-05-16 08:11 UTC, DropD requested changes

2025-04-15 08:37 UTC, havogt commented
obsolete

2025-04-15 08:37 UTC, closed without merging