feat[next][dace]: add workflow for dace fieldview backend
GridTools/gt4py pull request #1623
Opened 2024-09-02 04:59 UTC by edopao

2024-09-05 12:58 UTC, edopao commented
Based on latest discussion in GTIR project, the ITIR dace backend will soon be removed so won't need this PR, which tried to share common code between ITIR and GTIR dace backends.

2024-09-19 07:31 UTC, havogt requested changes

2024-09-19 07:31 UTC, havogt commented on src/gt4py/next/program_processors/runners/dace_fieldview/workflow.py
> +            ...
Is this still needed? If yes we should improve the pattern...

2024-09-19 10:17 UTC, havogt approved these changes

2024-09-19 10:27 UTC, merged