feat[next]: Support for direct field operator call with domain arg
GridTools/gt4py pull request #1779
Opened 2024-12-10 19:29 UTC by tehrengruber

2024-12-10 19:37 UTC, tehrengruber commented on src/gt4py/next/ffront/past_process_args.py
> +def _field_constituents_range_and_dims(
This part of the code-base is an extremely poor state, let's not prettify a blobfish and invest time on improving this here.

2024-12-10 20:16 UTC, havogt requested changes
Please split into 2 PRs.

2025-01-15 17:34 UTC, havogt commented
Is #1780 required for this to work, I still don't understand that part...

2025-01-17 18:11 UTC, havogt approved these changes

2025-01-18 14:33 UTC, merged