Remove and fix AugAssign, update dawn backend
GridTools/gt4py pull request #198
Opened 2020-09-26 00:19 UTC by jdahm

2020-09-28 09:44 UTC, DropD requested changes
I don't really see the added test, rather the tests are unchanged but went from passing to failing.

Note that the changes to the tests in the first commit were not accompanied by appropriate changes to the validation:

```python
# stencil
field_a -= field_b
...

# validation
field_a = (field_a + 1.0) * 2.0 - field_b  # <-- should fail in any case
field_a = (field_a - field_b + 1.0) * 2.0  # should work if AugAssign works
```

2020-09-28 19:27 UTC, jdahm commented
@DropD Yes, I realized that my test additions were incorrect. I suspect the current code is incorrect, but the tests are passing. I am looking into that inconsistency.

2020-09-29 18:52 UTC, jdahm commented
@DropD I found it - the fields needed subscripts, e.g. `field_a[...]`.

2020-09-29 22:25 UTC, jdahm commented
@twicki and I had to wrap `visit` call with `gt_ir.utils.make_expr` to fix a failing test as a result of fixing the AugAssign 👍 .

2020-09-30 05:10 UTC, jdahm commented
This is ready to be merged after the re-review!

2020-09-30 12:15 UTC, DropD approved these changes
Nice, thanks for also fixing the test

2020-09-30 12:23 UTC, merged