Support external imports in functions
GridTools/gt4py pull request #271
Opened 2020-12-01 05:48 UTC by jdahm

## Description

Support external imports in functions. This is an important feature for the regions PRs, since regions are often deeply buried in function calls. Example:

```python
def fill_4corners_x(q: sd):
    from __externals__ import i_end, i_start, j_end, j_start

    # copy field
    q_out = q

    # Southwest
    with parallel(region[i_start - 2, j_start - 1]):
        q_out = q[1, 2, 0]
    with parallel(region[i_start - 1, j_start - 1]):
        q_out = q[0, 1, 0]

    # Southeast
    with parallel(region[i_end + 2, j_start - 1]):
        q_out = q[-1, 2, 0]
    with parallel(region[i_end + 1, j_start - 1]):
        q_out = q[0, 1, 0]

    # Northwest
    with parallel(region[i_start - 1, j_end + 1]):
        q_out = q[0, -1, 0]
    with parallel(region[i_start - 2, j_end + 1]):
        q_out = q[1, -2, 0]

    # Northeast
    with parallel(region[i_end + 1, j_end + 1]):
        q_out = q[0, -1, 0]
    with parallel(region[i_end + 2, j_end + 1]):
        q_out = q[-1, -2, 0]

    return q_out
```

## Requirements

Before submitting this PR, please make sure:

- [ ] The code builds cleanly without new errors or warnings
- [ ] The code passes all the existing tests
- [ ] If this PR adds a new feature, new tests have been added to test these
new features
- [ ] All relevant documentation has been updated or added

Additionally, if this PR contains code authored by new contributors:

- [ ] All the authors are covered by a valid contributor assignment agreement,
signed by the employer if needed, provided to ETH Zurich
- [ ] The names of all the new contributors have been added to an updated
version of the AUTHORS.rst file included in the PR

2020-12-01 16:05 UTC, egparedes requested changes
Thanks for finding and fixing this bug. The PR looks fine but there is a typo in the code that should make the test fail. Please fix the typo and verify that the added tests is well defined and covers all the corner cases.

2020-12-01 16:05 UTC, egparedes commented on src/gt4py/frontend/gtscript_frontend.py
> +                        add_func_externals[imported_name] = sub_context[imported_value]
I guess this should be:

```suggestion
                        new_func_externals[imported_name] = sub_context[imported_value]
```

If the tests are passing even with this typo in the code, there is something else wrong either in the code or in the tests.

2020-12-01 16:33 UTC, jdahm commented on src/gt4py/frontend/gtscript_frontend.py
> +        )
I keep forgetting that comprehensions can have if statements on them! Thanks for the suggestion.

2020-12-01 18:40 UTC, jdahm commented
GitHub Actions failed here. There is no issue with formatting. I'll try to push a minor commit so that it rebuilds after ensuring there is full test coverage.

2020-12-01 20:23 UTC, jdahm commented on tests/test_unittest/test_gtscript_frontend.py
> +        }
For reasons that still elude me, this test is necessary. I thought this was covered below, but this uncovered the need for the additional annotate call at gtscript_frontend.py:1477.

2020-12-02 03:57 UTC, jdahm commented on tests/test_unittest/test_gtscript_frontend.py
> +            "tests.test_unittest.test_gtscript_frontend.func_nest1.func_nest2",
Externals captured implicitly get the fully qualified name.

2020-12-02 17:19 UTC, egparedes approved these changes
The code looks correct although it's hard to say if all the corner cases are covered. Probably the cause of all the weird cases is allowing calls to undecorated functions, which I still think feels like the wrong pattern. Anyway, if you think this PR is done, we can merge it.

2020-12-02 18:13 UTC, jdahm commented
Yes, I believe this PR is ready, but should have a follow-up that cleans up the annotation system.

2020-12-03 14:10 UTC, merged