Optimization Pass: Merge Adjacent MaskStmts in OIR
GridTools/gt4py pull request #400
Opened 2021-04-16 13:48 UTC by fthaler

## Description

A new optimization pass, merging adjacent MaskStmts if the masks are identical (and not re-written in the first).

## Requirements

Before submitting this PR, please make sure:

- [ ] The code builds cleanly without new errors or warnings
- [ ] The code passes all the existing tests
- [ ] If this PR adds a new feature, new tests have been added to test these
new features
- [ ] All relevant documentation has been updated or added

Additionally, if this PR contains code authored by new contributors:

- [ ] All the authors are covered by a valid contributor assignment agreement,
signed by the employer if needed, provided to ETH Zurich
- [ ] The names of all the new contributors have been added to an updated
version of the AUTHORS.rst file included in the PR

2021-04-27 07:14 UTC, fthaler commented
bors try

2021-04-28 06:30 UTC, fthaler commented
bors try

2021-04-30 07:30 UTC, havogt requested changes

2021-04-30 07:30 UTC, havogt commented on src/gtc/passes/oir_optimizations/mask_stmt_merging.py
> +                    AccessCollector.apply(merged[-1].body).write_fields()
Please add a test for this branch.

2021-04-30 07:56 UTC, fthaler commented on src/gtc/passes/oir_optimizations/mask_stmt_merging.py
> +                    AccessCollector.apply(merged[-1].body).write_fields()
Done.

2021-04-30 13:41 UTC, fthaler commented
bors try

2021-05-18 07:32 UTC, fthaler commented
bors try

2021-05-28 07:25 UTC, egparedes commented
@fthaler @havogt What is still missing to merge this PR?

2021-06-01 06:41 UTC, fthaler commented
> @fthaler @havogt What is still missing to merge this PR?

Just @havogt’s second review round and approval is missing as far as I can tell.

2021-06-01 07:15 UTC, havogt approved these changes

2021-06-01 08:21 UTC, fthaler commented
bors try

2021-06-01 09:44 UTC, merged