Cleanup frontend tests
GridTools/gt4py pull request #425
Opened 2021-06-02 23:33 UTC by jdahm

## Description

Clean up tests for `gtscript_frontend.py`.

2021-06-03 16:59 UTC, jdahm commented on tests/test_unittest/test_gtscript_frontend.py
>  def compile_definition(
This could be instead called `parse_definition`.

2021-06-07 10:49 UTC, tehrengruber requested changes
The inspection of the stack inside `parse_definition` is not a good solution. See my comment for an easy to implementable solution.

2021-06-07 10:49 UTC, tehrengruber commented on tests/test_unittest/test_gtscript_frontend.py
> +def parse_defintion(
```suggestion
def parse_definition(
```

2021-06-07 10:49 UTC, tehrengruber commented on tests/test_unittest/test_gtscript_frontend.py
> +        context=stack[0].f_locals["self"].__class__.__name__, method=stack[3], id_version=id_version
As far as I can see this only works for the stack structure used by convention here, but is rather fragile and error prone. It should be the responsibility of the caller not the callee to specify the module and method. I propose we use something like this:
```
parse_definition(..., module=self.__class__.__name__, method=inspect.stack()[0][3])
```
If you want to append the `id_version` to the module name you can still do that inside `parse_definition`.

2021-06-07 17:24 UTC, jdahm commented
@tehrengruber Thanks for reviewing! I'll implement those changes right now.

2021-06-07 17:28 UTC, jdahm commented on tests/test_unittest/test_gtscript_frontend.py
> +        context=stack[0].f_locals["self"].__class__.__name__, method=stack[3], id_version=id_version
> As far as I can see this only works for the stack structure used by convention here, but is rather fragile and error prone

Correct! I wasn't happy with it... Glad you found a nice solution. Though, it seems like the `module` isn't even used...

2021-06-16 18:05 UTC, merged