Fix origin offseting if i or j is not present in field for gtc backends
GridTools/gt4py pull request #435
Opened 2021-06-17 07:07 UTC by gronerl

It seems that `sid::shift_sid_origin` does not match origin dimensions to dimension names but instead offsets them as they are in order. Therefor the order of shifting and renaming has to be changed for the gtc backends. Weirdly, changing this makes the renaming not have effect when querying strides through dimension names (see dace backend). We can put the index of the dimension instead.  

Proper fix should probably go into gridtools repo, this works though.

2021-06-17 07:07 UTC, gronerl commented
bors try

2021-06-17 09:07 UTC, gronerl commented
bors try

2021-06-18 07:26 UTC, havogt commented
Before we merge this, we need to fully understand the problem.
- I understand the part about `sid_shift_origin`. @anstaf Let's discuss if we need another API for `sid_shift_origin` that takes also `stride`. It's not strictly necessary, the implementation in this PR is ok.
- I don't fully understand. Can we make a reproducible? It's either a bug, then your workaround will break once the bug is fixed, or it's wrong use of sid.

2021-06-18 07:32 UTC, gronerl commented
Why do you think it will break once the (possible?) bug is fixed? When applying sid_shift_origin, the dimensions are always in the right order.

2021-06-18 07:41 UTC, gronerl commented
Ah I guess your second bullet refers to the changes in the dace backend.

2021-06-18 12:21 UTC, havogt commented
Sorry, yes, in the second point I forgot to link it to the second problem.
Here my updated assessment:
- The fix for the first part is correct, as discussed in the meeting. We could improve the code by using a hymap for the offsets.
- After looking closer, it seems there is a bug in the SID implementation, regarding your second problem (DaCe backend).

2021-06-18 14:02 UTC, havogt requested changes

2021-06-18 14:02 UTC, havogt commented on src/gt4py/backend/gtc_backend/dace/backend.py
> +
in the line above there is a bug: it should be `gt::sid::get_strides`. `sid_` is wrong.

2021-06-18 14:20 UTC, gronerl commented
bors try

2021-06-22 08:36 UTC, havogt approved these changes

2021-06-22 09:06 UTC, merged