Fixes serialization roundtrip of enums in eve (issue #352)
GridTools/gt4py pull request #612
Opened 2022-01-14 10:38 UTC by tehrengruber

## Description

@egparedes The issue lied in ours validators not Pydantic...

## Requirements

Before submitting this PR, please make sure:

- [ ] You have run the code checks, tests and documentation build successfully
- [ ] All fixes and all new functionality are tested and documentation is up to date
- [ ] You looked at the [review checklist](https://github.com/GridTools/gt4py/blob/master/REVIEW_CHECKLIST.txt)

Additionally, if this PR contains code authored by new contributors:

- [ ] All the authors are covered by a valid contributor assignment agreement,
signed by the employer if needed, provided to ETH Zurich
- [ ] The names of all the new contributors have been added to an updated
version of the AUTHORS.rst file included in the PR

2022-01-14 10:40 UTC, tehrengruber commented
bors try

2022-01-18 11:42 UTC, egparedes requested changes
Great simple fix for the long-standing issue, thanks for looking into that. I only have a question and a quick fix.

2022-01-18 11:42 UTC, egparedes commented on src/eve/type_definitions.py
> +            v = cls[v]
Either `v` is guaranteed to be a `str` and thus the type annotation is wrong or the call to `hasattr` can trigger an Exception if something else than a string is passed. I think the safe way to check if the passed value is a string with the name of an enum member is using the `__members__` dictionary of the enum class:

```suggestion
    def _value_validator(cls, v: Any) -> StrEnum:
        if isinstance(v, str) and v in cls.__members__:
            v = cls[v]
```

It's probably worth to add a comment here mentioning that the passed string is first looked up as a enum member and then as a enum value.

2022-01-18 11:42 UTC, egparedes commented on tests/eve_tests/definitions.py
> -    int_sequence = make_collection_value(int, collection_type=tuple, length=3)
I don't understand this change. Why is it needed?

2022-01-27 10:41 UTC, tehrengruber commented
bors try

2022-01-27 12:23 UTC, egparedes commented on src/eve/type_definitions.py
> +        if hasattr(cls, v):
What does pydantic uses as default for the serialization: the name or the value? If it always uses of them, we should also probably use the same

2022-01-27 14:08 UTC, tehrengruber commented
bors try

2022-01-27 15:29 UTC, tehrengruber commented on src/eve/type_definitions.py
> +        if hasattr(cls, v):
Pydantic always uses the value for serialization (for `dict` it is configurable whether the enum value or instance is used). I removed the `str` case.

2022-01-28 13:26 UTC, egparedes approved these changes
Looks good.

2022-01-28 14:40 UTC, merged