Fix bug in computing block extents
GridTools/gt4py pull request #615
Opened 2022-01-14 20:55 UTC by jdahm

## Description

When looping over the stencil and computing block field and block extents, only the vertical loop sections were visited in reverse order, whereas it should have been the horizontal executions.

2022-01-17 07:57 UTC, havogt reviewed
As you already indicated in the slack message, we should add tests here.

2022-01-19 17:30 UTC, jdahm commented
bors try

2022-01-20 09:54 UTC, fthaler requested changes
Looks good, just added some minor suggestions about the provided test. A bit surprising that there weren’t more errors because of this bug.

2022-01-20 09:54 UTC, fthaler commented on tests/test_unittest/test_gtc/test_passes/test_oir_optimizations/test_horizontal_execution_merging.py
> +    assert block_extents[id(hexecs[0])] != Extent.zeros(ndims=2)
Better check what the value should be than what it should not be.

2022-01-20 09:54 UTC, fthaler commented on tests/test_unittest/test_gtc/test_passes/test_oir_optimizations/test_horizontal_execution_merging.py
> +            ),
Just having `HorizontalExecutionFactory(body__0__left__name="tmp")` should also work. You do not have to specify the `right__name`, a unique value is generated automatically (and omission helps the reader to understand that its value is irrelevant).

2022-01-20 09:54 UTC, fthaler commented on tests/test_unittest/test_gtc/test_passes/test_oir_optimizations/test_horizontal_execution_merging.py
> +                body=[AssignStmtFactory(left__name="out", right__name="tmp", right__offset__i=1)]
Same here.

2022-01-21 00:38 UTC, jdahm commented
bors try

2022-01-21 05:34 UTC, fthaler approved these changes

2022-01-21 05:35 UTC, merged