load_retries and load_retry_delay should be ints
GridTools/gt4py pull request #712
Opened 2022-04-05 03:18 UTC by jdahm

## Description

The environment variables should be interpreted as ints.

2022-04-05 08:11 UTC, egparedes requested changes
Thanks for the PR, it makes a lot of sense but I think it should be done in a safer way.

2022-04-05 08:48 UTC, gronerl commented on src/gt4py/config.py
> +    "load_retry_delay": int(os.environ.get("GT_CACHE_LOAD_RETRY_DELAY", 100)),  # unit miliseconds
Is that really safer? As a user I'm pretty sure I would want it to raise rather than compilation to fail for a reason that I don't understand.

2022-04-06 08:19 UTC, egparedes commented on src/gt4py/config.py
> +    "load_retry_delay": int(os.environ.get("GT_CACHE_LOAD_RETRY_DELAY", 100)),  # unit miliseconds
Ok, yes, I think you're right. I'm not so sure if the error message will provide enough context to catch the error, but if you both think so, it's fine for me then.

2022-04-06 08:20 UTC, egparedes approved these changes
After the discussion in the comments I realized my suggestion was wrong so this looks good for me.

2022-04-06 10:09 UTC, egparedes commented
bors try

2022-04-06 12:39 UTC, gronerl commented on src/gt4py/config.py
> +    "load_retry_delay": int(os.environ.get("GT_CACHE_LOAD_RETRY_DELAY", 100)),  # unit miliseconds
We could of course try...except and raise a 
`ValueError("GT_CACHE_LOAD_RETRIES must be an integer.")`

2022-04-06 16:13 UTC, jdahm commented on src/gt4py/config.py
> +    "load_retry_delay": int(os.environ.get("GT_CACHE_LOAD_RETRY_DELAY", 100)),  # unit miliseconds
I like that. I'll make a wrapper function like `get_env_var_as(name: str, type: Type[T]) -> T` before we merge this.

2022-04-06 18:02 UTC, jdahm commented
bors try

2022-04-07 17:04 UTC, jdahm commented on src/gt4py/config.py
> +    "load_retry_delay": int(os.environ.get("GT_CACHE_LOAD_RETRY_DELAY", 100)),  # unit miliseconds
Actually, in the spirit of not over-complicating things, I'll just merge this as-is. We can always change this later.

2022-04-07 17:04 UTC, merged