Functional: Common Subexpression Elimination
GridTools/gt4py pull request #754
Opened 2022-04-29 13:00 UTC by fthaler

## Description

Implements Common Subexpression Elimination (CSE) as an IR pass.

## Requirements

Before submitting this PR, please make sure:

- [ ] You have run the code checks, tests and documentation build successfully
- [ ] All fixes and all new functionality are tested and documentation is up to date
- [ ] You looked at the [review checklist](https://github.com/GridTools/gt4py/blob/master/REVIEW_CHECKLIST.txt)

Additionally, if this PR contains code authored by new contributors:

- [ ] All the authors are covered by a valid contributor assignment agreement,
signed by the employer if needed, provided to ETH Zurich
- [ ] The names of all the new contributors have been added to an updated
version of the AUTHORS.rst file included in the PR

2022-05-05 13:45 UTC, DropD requested changes

2022-05-05 13:45 UTC, DropD commented on src/functional/iterator/transforms/cse.py
> +class CollectSubexpressions(NodeVisitor):
How about a docstring with an example (doctest if possible), similar to the passes in field view? This is not a prototype anymore.

2022-05-05 13:45 UTC, DropD commented on src/functional/iterator/transforms/cse.py
> +class CSE(NodeTranslator):
doctoring, see above.

2022-05-12 10:00 UTC, fthaler commented
It’s actually unneeded after the updated reduction unrolling strategy, so I will close it.

2022-05-12 10:00 UTC, closed without merging