Functional: domain -> cartesian_domain | unstructured_domain in Iterator IR
GridTools/gt4py pull request #839
Opened 2022-06-27 12:23 UTC by havogt

Introduces `cartesian_domain` and `unstructured_domain` in Iterator IR. The semantics of `unstructured_domain` arguments is `unstructured_domain(horizontal_named_range, vertical_named_range)`. Currently this is not checked. It requires to encode this information in the `Dimension` which will come with the backend integration.

2022-06-29 13:37 UTC, DropD requested changes
Looks good overall, just some minor improvements.

2022-06-29 13:37 UTC, DropD commented on tests/functional_tests/ffront_tests/test_domain_decution.py
> +def test_domain_deduction():
Might be useful to separate these more, also to document more clearly that this operates in several modes (pure deduction, overriding deduction with user choice, failing if user choice is not appropriate).

2022-06-29 14:43 UTC, havogt commented on src/functional/ffront/decorator.py
> +                            offsets_and_dimensions.add(c)
Thanks for pointing out. I was lazy...

2022-06-30 09:24 UTC, DropD approved these changes

2022-06-30 09:25 UTC, merged