Cache settings
GridTools/gt4py pull request #892
Opened 2022-08-10 06:41 UTC by tehrengruber

This PR adds the ability to pass the cache directory (both `root_path` and `dir_name`) to the `stencil` decorator. In FVM we compile multiple stencils in parallel and use by default use a common cache path project-wide regardless of where the driver resides. Setting this directory in our stencil wrapper lead to a race-condition which we can avoid with the changes here.

2022-08-10 06:42 UTC, tehrengruber commented
bors try

2022-08-11 12:12 UTC, DropD requested changes
👍 There is really just this one typo...

2022-08-11 12:12 UTC, DropD commented on src/gt4py/gtscript.py
> +        raise ValueError(f"Invalid 'cache_settings' dictionary ('{rebuild}')")
copy pasta? 
```suggestion
        raise ValueError(f"Invalid 'cache_settings' dictionary ('{cache_settings}')")
```

2022-08-11 12:12 UTC, DropD commented on src/gt4py/gtscript.py
> +        cache_settings=cache_settings,
Have you considered inlining the if block above?
```suggestion
        cache_settings=cache_settings or {},
```

2022-08-11 12:13 UTC, tehrengruber commented on src/gt4py/gtscript.py
> +        raise ValueError(f"Invalid 'cache_settings' dictionary ('{rebuild}')")
wups

2022-08-11 12:16 UTC, DropD approved these changes

2022-08-12 08:37 UTC, merged