Functional: Scans: More General ‘Backward’ Unstructured Domain Analysis, Better Shift Analysis, Cleanups
GridTools/gt4py pull request #915
Opened 2022-08-25 12:27 UTC by fthaler

## Description

Implements a more general ‘backward’ unstructured domain/extent analysis and proper tracing of shifts in functions etc. Further, the domain analysis part is cleaned up a bit.

## Requirements

Before submitting this PR, please make sure:

- [ ] You have run the code checks, tests and documentation build successfully
- [ ] All fixes and all new functionality are tested and documentation is up to date
- [ ] You looked at the [review checklist](https://github.com/GridTools/gt4py/blob/master/REVIEW_CHECKLIST.txt)

Additionally, if this PR contains code authored by new contributors:

- [ ] All the authors are covered by a valid contributor assignment agreement,
signed by the employer if needed, provided to ETH Zurich
- [ ] The names of all the new contributors have been added to an updated
version of the AUTHORS.rst file included in the PR

2022-08-25 13:26 UTC, fthaler commented
pre-commit failing because of https://github.com/GridTools/gt4py/pull/913

2022-10-13 09:27 UTC, havogt requested changes
We probably need to make sure that this problem is resolved, otherwise we might run into strange issues in the future.

2022-10-13 09:27 UTC, havogt commented on tests/functional_tests/iterator_tests/test_fvm_nabla.py
> +    if lift_mode != LiftMode.FORCE_INLINE:
We had a discussion yesterday about the problem of lift and concluded that it is not broken in the part where we thought it is. Let's have a chat next week.

2022-10-25 17:15 UTC, havogt commented on tests/functional_tests/iterator_tests/test_fvm_nabla.py
> +    if lift_mode != LiftMode.FORCE_INLINE:
We should resolve this separately.

2022-10-25 17:16 UTC, merged